CREATE TABLE sensor_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sensor_type VARCHAR(255) NOT NULL,
    sensor_value DOUBLE NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE BME280_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    temperature DOUBLE NOT NULL,
    humidity DOUBLE NOT NULL,
    pressure DOUBLE NOT NULL,
    status VARCHAR(10),
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE PMS5003_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pm1_0 INTEGER NOT NULL,
    pm2_5 INTEGER NOT NULL,
    pm10 INTEGER NOT NULL,
    status VARCHAR(10),
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE SCD40_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    co2 INTEGER NOT NULL,
    temperature DOUBLE NOT NULL,
    humidity DOUBLE NOT NULL,
    status VARCHAR(10),
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE SGP40_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    voc_index INTEGER NOT NULL,
    status VARCHAR(10),
    timestamp TIMESTAMP NOT NULL
);
